defaults: &defaults
  docker:
    - image: circleci/node:8.10-stretch

version: 4
jobs:
  bootstrap:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dependency hash
          command: yarn run create-dependency-hash
      - restore_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Archive dependencies
          command: yarn run archive:dependencies
      - save_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
          paths:
            - .archives/dependencies.tar.gz
  package-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dependency hash
          command: yarn run create-dependency-hash
      - restore_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
      - run:
          name: Extract dependencies
          command: yarn run extract:dependencies
      - run:
          name: Build all packages
          command: yarn build
      - run:
          name: Archive builds
          command: yarn run archive:builds
      - save_cache:
          key: package-builds-{{ .Revision }}
          paths:
            - .archives/builds.tar.gz
  react-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dependency hash
          command: yarn run create-dependency-hash
      - restore_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
      - restore_cache:
          key: package-builds-{{ .Revision }}
      - run:
          name: Extract dependencies and builds
          command: yarn run extract
      - run:
          name: Lint (React)
          command: yarn lint
      - run:
          name: Run Jest Tests
          command: yarn test-ci
          working_directory: packages/storybook
      - store_artifacts:
          path: packages/storybook/coverage
  visual-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dependency hash
          command: yarn run create-dependency-hash
      - restore_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
      - restore_cache:
          key: package-builds-{{ .Revision }}
      - run:
          name: Extract dependencies and builds
          command: yarn run extract
      - run:
          name: Build Test Storybook Server
          command: yarn storybook-test-build
          working_directory: packages/storybook
      - run:
          name: Serve Test Storybook
          command: yarn storybook-test-serve
          background: true
          working_directory: packages/storybook
      - run:
          name: Start HTTP Server
          command: yarn vanilla-test-serve
          background: true
          working_directory: packages/storybook
      - run:
          name: Run Visual Regression Tests
          command: yarn gemini-ci
          working_directory: packages/storybook
      - store_artifacts:
          path: packages/storybook/gemini-report
  playground-deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dependency hash
          command: yarn run create-dependency-hash
      - restore_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
      - restore_cache:
          key: package-builds-{{ .Revision }}
      - run:
          name: Extract dependencies and builds
          command: yarn run extract
      - run:
          name: Deploy React playground website
          command: yarn deploy-playground $PLAYGROUND_DOMAIN
          working_directory: packages/react
  canary-packages-deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dependency hash
          command: yarn run create-dependency-hash
      - restore_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
      - restore_cache:
          key: package-builds-{{ .Revision }}
      - run:
          name: Extract dependencies and builds
          command: yarn run extract
      - run:
          name: Add auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Deploy pre-release versions of packages
          command: yarn publish-canary
  storybook-branch-deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dependency hash
          command: yarn run create-dependency-hash
      - restore_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
      - restore_cache:
          key: package-builds-{{ .Revision }}
      - run:
          name: Extract dependencies and builds
          command: yarn run extract
      - run:
          name: Deploy Storybook
          command: yarn storybook-deploy --domain `echo hig-$CIRCLE_BRANCH.surge.sh | awk 'echo gsub(/\//, "-")'`
          working_directory: packages/storybook
  packages-deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create dependency hash
          command: yarn run create-dependency-hash
      - restore_cache:
          key: dependencies-{{ checksum ".dependency-hash" }}
      - restore_cache:
          key: package-builds-{{ .Revision }}
      - run:
          name: Extract dependencies and builds
          command: yarn run extract
      - run:
          name: Add auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Deploy hig-react
          command: node ./scripts/publish-if-needed/index.js react
      - run:
          name: Deploy hig-interface
          command: node ./scripts/publish-if-needed/index.js interface
      - run:
          name: Deploy hig-vanilla
          command: node ./scripts/publish-if-needed/index.js vanilla
workflows:
  version: 2
  build-test-validate-and-deploy:
    jobs:
      - bootstrap
      - package-build:
          requires:
            - bootstrap
      - react-test:
          requires:
            - package-build
      - visual-test:
          requires:
            - package-build
      - playground-deploy:
          requires:
            - react-test
            - visual-test
          filters:
            branches:
              only: development
      - canary-packages-deploy:
          filters:
            branches:
              ignore:
                - master
          requires:
            - react-test
            - visual-test
      - storybook-branch-deploy:
          filters:
            branches:
              ignore:
                - development
                - master
          requires:
            - react-test
            - visual-test
      - packages-deploy:
          requires:
            - react-test
            - visual-test
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
